# Generated by Django 5.0.1 on 2024-01-22 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_postnewview_postnewmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postnewmodel',
            name='photo',
            field=models.ImageField(upload_to='photo/%Y/%m/%d'),
        ),
    ]
