# Generated by Django 5.0.1 on 2024-01-23 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='photo',
            new_name='PRF_image',
        ),
    ]
