# Generated by Django 5.0.1 on 2024-01-24 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_post_prf_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='PRF_image',
            field=models.ImageField(default='default.jpg', upload_to='photo/%Y/%m/%d'),
        ),
    ]
