# Generated by Django 5.0.1 on 2024-01-24 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_post_prf_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='PRF_image',
            new_name='photo',
        ),
    ]
