# Generated by Django 5.0.1 on 2024-01-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='about',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(default='null', upload_to='photo/%y/%m/%d'),
        ),
    ]
